### ISSUE TITLE
Account cannot be accessed anymore when you change your mail on Discourse

### ISSUE THREAD

**Issue by rugk** [mozilla/discourse#191] opened 2019-04-01 13:11 UTC
## STR

1. Login/auth with GitHub.
2. Now when you create a new user on Discourse then, you cannot change your mail. (so far so expected.)
3. Go into the settings of Discourse. There you can change your mail.
4. Now, change it.

### What happens

As your mail is now different than on GitHub, it does not allow you to login to Discourse anymore.

### What should happen

Whatever… let me login.

## Related

* It's likely the same underlying cause, but if you change your mail on GitHub the same happens: https://github.com/mozilla/discourse/issues/176
* whole background story can be seen in this thread: https://discourse.mozilla.org/t/auth0-creates-new-account-when-github-mail-changes/36362/10

### Suggested solution

* short-term: don't let me change my mail on Discourse if this leads to locking myself out :roll_eyes: 
* long-term: don't do auth with mail, but with my GitHub _account_ (and then let me change my mail to whatever I like)

## Personal issue

~~@LeoMcA, I need your help again. As you see I was so stupid to do the steps I described above yesterday and thought nothing would break. I mean, seeing the whole issue before I should not have tried that… arrgh…~~ (solved)

**Comment by rugk** [comment] 2019-04-01 13:24
@LeoMcA, ah forget it. I found a workaround: I can of course login with my new mail using this "passwordless" login where I need to click on the mail. Then I can click that link, change my mail back to the GitHub one and login again.

So my personal issue is solved. That issue here not.

**Comment by LeoMcA** [comment] 2019-04-01 14:20
Duplicate of https://github.com/mozilla/discourse/issues/176

**Closed by LeoMcA** 2019-04-01 14:20 UTC
